name: digital_wallet
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dartz:
  http:
  shared_preferences:
  get_it:
  bloc:
  equatable:
  flutter_screenutil:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen:
  flutter_gen_runner:
  flutter_lints: ^3.0.0

flutter_gen:
  integration:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/colors.xml


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/fonts/
    - assets/png/

  fonts:
    - family: PlusJakartaSans-Bold
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf

    - family: PlusJakartaSans-BoldItalic
      fonts:
        - asset: fonts/PlusJakartaSans-BoldItalic.ttf

    - family: PlusJakartaSans-ExtraBold
      fonts:
        - asset: fonts/PlusJakartaSans-ExtraBold.ttf

    - family: PlusJakartaSans-ExtraBoldItalic
      fonts:
        - asset: fonts/PlusJakartaSans-ExtraBoldItalic.ttf

    - family: PlusJakartaSans-ExtraLight
      fonts:
        - asset: fonts/PlusJakartaSans-ExtraLight.ttf

    - family: PlusJakartaSans-ExtraLightItalic
      fonts:
        - asset: fonts/PlusJakartaSans-ExtraLightItalic.ttf

    - family: PlusJakartaSans-Italic
      fonts:
        - asset: fonts/PlusJakartaSans-Italic.ttf

    - family: PlusJakartaSans-Light
      fonts:
        - asset: fonts/PlusJakartaSans-Light.ttf

    - family: PlusJakartaSans-Light-Italic
      fonts:
        - asset: fonts/PlusJakartaSans-LightItalic.ttf


    - family: PlusJakartaSans-Medium
      fonts:
        - asset: fonts/PlusJakartaSans-Medium.ttf


    - family: PlusJakartaSans-MediumItalic
      fonts:
        - asset: fonts/PlusJakartaSans-MediumItalic.ttf

    - family: PlusJakartaSans-Regular
      fonts:
        - asset: fonts/PlusJakartaSans-Regular.ttf

    - family: PlusJakartaSans-SemiBold
      fonts:
        - asset: fonts/PlusJakartaSans-SemiBold.ttf

    - family: PlusJakartaSans-SemiBoldItalic
      fonts:
        - asset: fonts/PlusJakartaSans-SemiBoldItalic.ttf


  #          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

